Selection.create(communityurl: "SEED EXAMPLE (all widgets enabled)",
		coloraccent1: "777879",
		coloraccent2: "777379",
		colorhighlight: "bada55",
		herocarousel: true,
		heroslide1headerline: "Welcome - Slide 1",
		heroslide1textparagraph: "Slide 1 paragraph",
		heroslide1bgurl: "/userimages/accounts/XX/XXXXXX/hero-office.png",
		heroslide1button1name: "Button 1",
		heroslide1button1url: "#",
		heroslide1button2name: "Button 2",
		heroslide1button2url: "#",
		heroslide2headerline: "Slide 2 header",
		heroslide2textparagraph: "slide 2 paragraph",
		heroslide2bgurl: "/userimages/accounts/XX/XXXXXX/hero-office.png",
		heroslide2button1name: "Button 1",
		heroslide2button1url: "#",
		heroslide2button2name: "Button 2",
		heroslide2button2url: "#",
		heroslide3headerline: "Slide 3 header",
		heroslide3textparagraph: "Slide 3 paragraph",
		heroslide3bgurl: "/userimages/accounts/XX/XXXXXX/hero-office.png",
		heroslide3button1name: "Button 1",
		heroslide3button1url: "#",
		heroslide3button2name: "Button 2",
		heroslide3button2url: "#",
		welcomearea: true,
		welcomeareatext: "Welcome area text",
		activecampaigns: true,
		generaltext: true,
		textheaderline: "General Text Area Header",
		textparagraph: "General text area paragraph",
		pinnedideas: true,
		calloutideas: true,
		tags: true,
		video: true,
		videourl: "https://youtu.be/NugRZGDbPFU",
		footer: true,
		footercol1header: "Footer Col1 Header",
		footercol1item1title: "footercol1item1title",
		footercol1item1url: "#",
		footercol1item2title: "footercol1item2title",
		footercol1item2url: "#",
		footercol1item3title: "footercol1item3title",
		footercol1item3url: "#",
		footercol1item4title: ["footer-col1-item4-title",
		footercol1item4url: "#",
		footercol1item5title: "footer-col1-item5-title",
		footercol1item5url: "#",
		footercol2header: "footer-col2-header",
		footercol2item1title: "footer-col2-item1-title",
		footercol2item1url: "#",
		footercol2item2title: "footer-col2-item2-title",
		footercol2item2url: "#",
		footercol2item3title: "footer-col2-item3-title",
		footercol2item3url: "#",
		footercol2item4title: "footer-col2-item4-title"],
		footercol2item4url: "#",
		footercol2item5title: "footer-col2-item5-title",
		footercol2item5url: "#",
		footercol3header: "footer-col3-header",
		footercol3item1title: "footer-col3-item1-title",
		footercol3item1url: "#",
		footercol3item2title: "footer-col3-item2-title",
		footercol3item2url: "#",
		footercol3item3title: "footer-col3-item3-title",
		footercol3item3url: "#",
		footercol3item4title: "footer-col3-item4-title",
		footercol3item4url: "#",
		footercol3item5title: "footer-col3-item5-title",
		footercol3item5url: "#",
		footercol4header: "footer-col4-header",
		footercol4item1title: "footer-col4-item1-title",
		footercol4item1url: "#",
		footercol4item2title: "footer-col4-item2-title",
		footercol4item2url: "#",
		footercol4item3title: "footer-col4-item3-title",
		footercol4item3url: "#",
		footercol4item4title: "footer-col4-item4-title",
		footercol4item4url: "#",
		footercol4item5title: "footer-col4-item5-title",
		footercol4item5url: "#",
		horizontalcampaigns: "horiztonal-active-campaigns",
		headerlink1text: "headerlink1text",
		headerlink1url: "#",
		headerlink2text: "headerlink2text",
		headerlink2url: "#",
		headerlink3text: "headerlink3text",
		headerlink3url: "#",
		headerlink4text: "headerlink4text",
		headerlink4url: "#",	
		headerlink5text: "headerlink5text",
		headerlink5url: "#",						
		divbgimg: "/userimages/accounts/XX/XXXXXX/hero-office.png",
		animated: "animated",
		animatedbg: "/userimages/accounts/XX/XXXXXX/hero-office.png"

		)