class CreateSelection < ActiveRecord::Migration
  def up
  	create_table :selections do |t|
		t.string :communityurl
		t.string :coloraccent1
		t.string :coloraccent2
		t.string :colorhighlight
		t.boolean :herocarousel
		t.string :heroslide1headerline
		t.string :heroslide1textparagraph
		t.string :heroslide1bgurl
		t.string :heroslide1button1name
		t.string :heroslide1button1url
		t.string :heroslide1button2name
		t.string :heroslide1button2url
		t.string :heroslide2headerline
		t.string :heroslide2textparagraph
		t.string :heroslide2bgurl
		t.string :heroslide2button1name
		t.string :heroslide2button1url
		t.string :heroslide2button2name
		t.string :heroslide2button2url
		t.string :heroslide3headerline
		t.string :heroslide3textparagraph
		t.string :heroslide3bgurl
		t.string :heroslide3button1name
		t.string :heroslide3button1url
		t.string :heroslide3button2name
		t.string :heroslide3button2url
		t.string :welcomearea
		t.string :welcomeareatext
		t.string :activecampaigns
		t.boolean :generaltext
		t.string :textheaderline
		t.string :textparagraph
		t.boolean :pinnedideas
		t.boolean :calloutideas
		t.boolean :tags
		t.boolean :video
		t.string :videourl
		t.boolean :footer
		t.string :footercol1header
		t.string :footercol1item1title
		t.string :footercol1item1url
		t.string :footercol1item2title
		t.string :footercol1item2url
		t.string :footercol1item3title
		t.string :footercol1item3url
		t.string :footercol1item4title
		t.string :footercol1item4url
		t.string :footercol1item5title
		t.string :footercol1item5url
		t.string :footercol2header
		t.string :footercol2item1title
		t.string :footercol2item1url
		t.string :footercol2item2title
		t.string :footercol2item2url
		t.string :footercol2item3title
		t.string :footercol2item3url
		t.string :footercol2item4title
		t.string :footercol2item4url
		t.string :footercol2item5title
		t.string :footercol2item5url
		t.string :footercol3header
		t.string :footercol3item1title
		t.string :footercol3item1url
		t.string :footercol3item2title
		t.string :footercol3item2url
		t.string :footercol3item3title
		t.string :footercol3item3url
		t.string :footercol3item4title
		t.string :footercol3item4url
		t.string :footercol3item5title
		t.string :footercol3item5url
		t.string :footercol4header
		t.string :footercol4item1title
		t.string :footercol4item1url
		t.string :footercol4item2title
		t.string :footercol4item2url
		t.string :footercol4item3title
		t.string :footercol4item3url
		t.string :footercol4item4title
		t.string :footercol4item4url
		t.string :footercol4item5title
		t.string :footercol4item5url
  	end
  end

  def down
  	drop_table :selections
  end
end